# Generated by Django 5.1.3 on 2025-07-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="brief_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Brief Project Description"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="live_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
