# Generated by Django 5.1.3 on 2025-07-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_brief_description_project_live_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Detailed Project Description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tag_1",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Project Tag 1"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tag_2",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Project Tag 2"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tag_3",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Project Tag 3"
            ),
        ),
    ]
