# Generated by Django 4.2 on 2025-07-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_project_description_alter_project_tag_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_overview",
            field=models.TextField(
                blank=True, null=True, verbose_name="Project Overview"
            ),
        ),
    ]
