# Generated by Django 4.2 on 2025-07-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_project_project_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tech_used",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Use"),
        ),
    ]
